#!/bin/bash

RED='\033[0;31m'
NC='\033[0m' # No Color
CYAN='\033[0;36m'
YELLOW='\033[1;33m'

printf "${RED}I love Stack Overflow\n"
echo "test between"
printf "${YELLOW}I love Stack Overflow${NC}\n"
printf "${CYAN}I love Stack Overflow\n"



echo "${RED} important"
echo "${NC} normal"
